import RS.Classical.Deligne.AltPow
import RS.Classical.Deligne.AltPowAct
import RS.Classical.Deligne.BaseChangeAdjoint
import RS.Classical.Deligne.BaseChangeBiprod
import RS.Classical.Deligne.BaseChangeCoherence
import RS.Classical.Deligne.BaseChangeDatum
import RS.Classical.Deligne.BaseChangeFree
import RS.Classical.Deligne.BaseChangeLinear
import RS.Classical.Deligne.BaseChangeMonoidal
import RS.Classical.Deligne.BaseChangeTensor
import RS.Classical.Deligne.BaseChangeTransport
import RS.Classical.Deligne.BaseChangeZigzag
import RS.Classical.Deligne.BigTensor
import RS.Classical.Deligne.BigTensorUnit
import RS.Classical.Deligne.BiprodPow
import RS.Classical.Deligne.BiprodTransfer
import RS.Classical.Deligne.BlockUnits
import RS.Classical.Deligne.BraidCoherence
import RS.Classical.Deligne.ChainAlgebra
import RS.Classical.Deligne.ChainB
import RS.Classical.Deligne.ChainBGr
import RS.Classical.Deligne.ChainBGraded
import RS.Classical.Deligne.ChainBGradedLaws
import RS.Classical.Deligne.ChainBInd
import RS.Classical.Deligne.ChainBNonzero
import RS.Classical.Deligne.ChainBofA
import RS.Classical.Deligne.ChainBridge
import RS.Classical.Deligne.ChainDelta
import RS.Classical.Deligne.ChainIns
import RS.Classical.Deligne.ChainIns.Base
import RS.Classical.Deligne.ChainIns.FirstSlot
import RS.Classical.Deligne.ChainIns.SecondSlot
import RS.Classical.Deligne.ChainMul
import RS.Classical.Deligne.ChainMulHet
import RS.Classical.Deligne.ChainMulLaws
import RS.Classical.Deligne.ChainNonzero
import RS.Classical.Deligne.ChainShift
import RS.Classical.Deligne.ChainStage2
import RS.Classical.Deligne.ChainUnit
import RS.Classical.Deligne.CharSplit
import RS.Classical.Deligne.CommonAlgebra
import RS.Classical.Deligne.CoprodPreserve
import RS.Classical.Deligne.CountableDescent
import RS.Classical.Deligne.CountableDescentClose
import RS.Classical.Deligne.CountableNullstellensatz
import RS.Classical.Deligne.CoverFactor
import RS.Classical.Deligne.CycleSplit
import RS.Classical.Deligne.DayCalculus
import RS.Classical.Deligne.DayType
import RS.Classical.Deligne.DeligneAssembly
import RS.Classical.Deligne.DescentClose
import RS.Classical.Deligne.DevissageBound
import RS.Classical.Deligne.DoubledAbelian
import RS.Classical.Deligne.DoubledGrowth
import RS.Classical.Deligne.DoubledLine
import RS.Classical.Deligne.DoubledScalar
import RS.Classical.Deligne.DoubledSmall
import RS.Classical.Deligne.DoubledSplit
import RS.Classical.Deligne.Doubling
import RS.Classical.Deligne.DualityMate
import RS.Classical.Deligne.EvenEmbedMonoidal
import RS.Classical.Deligne.ExactFromShort
import RS.Classical.Deligne.FactorialBeats
import RS.Classical.Deligne.FibreAdditive
import RS.Classical.Deligne.FibreBridge
import RS.Classical.Deligne.FibreEps
import RS.Classical.Deligne.FibreExact
import RS.Classical.Deligne.FibreFaithful
import RS.Classical.Deligne.FibreFunctor
import RS.Classical.Deligne.FibreMix
import RS.Classical.Deligne.FibreMonoidal
import RS.Classical.Deligne.FibreMu
import RS.Classical.Deligne.FibreLinear
import RS.Classical.Deligne.FibreMuNat
import RS.Classical.Deligne.FibreOverComplex
import RS.Classical.Deligne.FibreOverSplitting
import RS.Classical.Deligne.FibreRestrict
import RS.Classical.Deligne.FibreStrong
import RS.Classical.Deligne.FiltNil
import RS.Classical.Deligne.FlatLimit
import RS.Classical.Deligne.FreeCollapseAlg
import RS.Classical.Deligne.FreeMixRetract
import RS.Classical.Deligne.FreeModAdjoint
import RS.Classical.Deligne.FreeModBiprod
import RS.Classical.Deligne.FreeModFunctor
import RS.Classical.Deligne.FreeModShuffle
import RS.Classical.Deligne.FreeModShuffleCoh
import RS.Classical.Deligne.FreeModTensor
import RS.Classical.Deligne.FreeSummand
import RS.Classical.Deligne.FreeNormalise
import RS.Classical.Deligne.FreeNormaliseBase
import RS.Classical.Deligne.FreeNormaliseStep
import RS.Classical.Deligne.FreePow
import RS.Classical.Deligne.FreePowDesc
import RS.Classical.Deligne.FreePowInsert
import RS.Classical.Deligne.FreeSlide
import RS.Classical.Deligne.FreeTwistPi
import RS.Classical.Deligne.GammaAlgebra
import RS.Classical.Deligne.GammaBiprod
import RS.Classical.Deligne.GammaCountable
import RS.Classical.Deligne.GammaComplex
import RS.Classical.Deligne.GammaModule
import RS.Classical.Deligne.GammaModuleFunctor
import RS.Classical.Deligne.GammaPair
import RS.Classical.Deligne.GammaPairAdd
import RS.Classical.Deligne.GammaPairFreeFree
import RS.Classical.Deligne.GammaPairFreeMix
import RS.Classical.Deligne.GammaPairNat
import RS.Classical.Deligne.GammaPairRetract
import RS.Classical.Deligne.GammaPairRetractRight
import RS.Classical.Deligne.GammaPairUnit
import RS.Classical.Deligne.GammaShift
import RS.Classical.Deligne.GammaTwistLeft
import RS.Classical.Deligne.GeneratorAlgebra
import RS.Classical.Deligne.GrowthDichotomy
import RS.Classical.Deligne.HomFinite
import RS.Classical.Deligne.HookMult
import RS.Classical.Deligne.HookZero
import RS.Classical.Deligne.IdemCut
import RS.Classical.Deligne.IdempotentLength
import RS.Classical.Deligne.ImageSubalgebra
import RS.Classical.Deligne.IndAllColim
import RS.Classical.Deligne.IndBigTensorUnit
import RS.Classical.Deligne.IndCoeq
import RS.Classical.Deligne.IndCompact
import RS.Classical.Deligne.IndDayClosure
import RS.Classical.Deligne.IndImage
import RS.Classical.Deligne.IndKill
import RS.Classical.Deligne.IndLocallyMixed
import RS.Classical.Deligne.IndMonoidal
import RS.Classical.Deligne.IndOfLinear
import RS.Classical.Deligne.IndOfMonoidal
import RS.Classical.Deligne.IndPointTensor
import RS.Classical.Deligne.IndSchur
import RS.Classical.Deligne.IndSchurKilled
import RS.Classical.Deligne.IndSimple
import RS.Classical.Deligne.IndSplit
import RS.Classical.Deligne.IndSplitSection
import RS.Classical.Deligne.IndTensorExact
import RS.Classical.Deligne.IndUnitNonzero
import RS.Classical.Deligne.InitDatum
import RS.Classical.Deligne.InitState
import RS.Classical.Deligne.InterchangeAct
import RS.Classical.Deligne.KernelPow
import RS.Classical.Deligne.KeyLemma
import RS.Classical.Deligne.KeyLemmaClose
import RS.Classical.Deligne.KeyLemmaData
import RS.Classical.Deligne.KillerNonempty
import RS.Classical.Deligne.KronKill
import RS.Classical.Deligne.LambdaCoend
import RS.Classical.Deligne.MixDegenerate
import RS.Classical.Deligne.MixShuffle
import RS.Classical.Deligne.MixShuffleLine
import RS.Classical.Deligne.MixSumPow
import RS.Classical.Deligne.MixWhisker
import RS.Classical.Deligne.MixWhiskerAll
import RS.Classical.Deligne.MixedConc
import RS.Classical.Deligne.MixedDiag
import RS.Classical.Deligne.MixedTransport
import RS.Classical.Deligne.ModAssoc
import RS.Classical.Deligne.ModBiprod
import RS.Classical.Deligne.ModAbelian
import RS.Classical.Deligne.ModContractL
import RS.Classical.Deligne.ModCross
import RS.Classical.Deligne.ModDual
import RS.Classical.Deligne.ModIns
import RS.Classical.Deligne.ModMulti
import RS.Classical.Deligne.ModMultiTriple
import RS.Classical.Deligne.ModPowCast
import RS.Classical.Deligne.ModPowDescent
import RS.Classical.Deligne.ModPowDescentClose
import RS.Classical.Deligne.ModPowStage
import RS.Classical.Deligne.ModSchur
import RS.Classical.Deligne.ModSchurSummand
import RS.Classical.Deligne.ModTensor
import RS.Classical.Deligne.ModZero
import RS.Classical.Deligne.MulBy
import RS.Classical.Deligne.MuInterchange
import RS.Classical.Deligne.NatChain
import RS.Classical.Deligne.NewtonConv
import RS.Classical.Deligne.NullPoint
import RS.Classical.Deligne.OddLineMap
import RS.Classical.Deligne.OddLinePairing
import RS.Classical.Deligne.OddParity
import RS.Classical.Deligne.OddPermSign
import RS.Classical.Deligne.OddSquare
import RS.Classical.Deligne.OddSquareIso
import RS.Classical.Deligne.PairCarrier
import RS.Classical.Deligne.PairMul
import RS.Classical.Deligne.PairPerm
import RS.Classical.Deligne.PermNat
import RS.Classical.Deligne.PermRepChar
import RS.Classical.Deligne.PieriPos
import RS.Classical.Deligne.PlainShuffle
import RS.Classical.Deligne.PointBaseChange
import RS.Classical.Deligne.PointFibre
import RS.Classical.Deligne.PointMonoidal
import RS.Classical.Deligne.PointMonoidal.Calculus
import RS.Classical.Deligne.PointMonoidal.Coherence
import RS.Classical.Deligne.PointMonoidal.Comparison
import RS.Classical.Deligne.PointMonoidal.Functor
import RS.Classical.Deligne.PointMonoidal.Residue
import RS.Classical.Deligne.PointTensor
import RS.Classical.Deligne.PowAct
import RS.Classical.Deligne.PowActMul
import RS.Classical.Deligne.PowChain
import RS.Classical.Deligne.PowCopairing
import RS.Classical.Deligne.PowDatum
import RS.Classical.Deligne.PowInduct
import RS.Classical.Deligne.PowMerge
import RS.Classical.Deligne.PowPairSucc
import RS.Classical.Deligne.PowPairing
import RS.Classical.Deligne.PowPoint
import RS.Classical.Deligne.PowSucc
import RS.Classical.Deligne.PowSuccMod
import RS.Classical.Deligne.PowTriangle
import RS.Classical.Deligne.PowZig
import RS.Classical.Deligne.PowZigzag
import RS.Classical.Deligne.PresentedQuotient
import RS.Classical.Deligne.Prop21
import RS.Classical.Deligne.Prop21Core
import RS.Classical.Deligne.Prop21General
import RS.Classical.Deligne.Prop29
import RS.Classical.Deligne.Prop29Close
import RS.Classical.Deligne.Prop29State
import RS.Classical.Deligne.Rappel210
import RS.Classical.Deligne.Rappel210Bridge
import RS.Classical.Deligne.Rappel210Chain
import RS.Classical.Deligne.Rappel210Close
import RS.Classical.Deligne.Rappel210Ind
import RS.Classical.Deligne.Rappel210Reduce
import RS.Classical.Deligne.RegularSum
import RS.Classical.Deligne.RhoBiprod
import RS.Classical.Deligne.RhoTwist
import RS.Classical.Deligne.RowColIdem
import RS.Classical.Deligne.SandwichMerge
import RS.Classical.Deligne.SandwichRetract
import RS.Classical.Deligne.SandwichZig
import RS.Classical.Deligne.ScalarBraiding
import RS.Classical.Deligne.ScalarLinear
import RS.Classical.Deligne.ScalarUnitEquiv
import RS.Classical.Deligne.ScalarUnitInd
import RS.Classical.Deligne.SchurTransport
import RS.Classical.Deligne.SchurVanishing
import RS.Classical.Deligne.SeedIns
import RS.Classical.Deligne.ShapeAlgebra
import RS.Classical.Deligne.ShapeFintype
import RS.Classical.Deligne.SignConj
import RS.Classical.Deligne.SimpleGenerator
import RS.Classical.Deligne.SmallReduction
import RS.Classical.Deligne.SimpleQuotient
import RS.Classical.Deligne.SimpleSplit
import RS.Classical.Deligne.SimplePoint
import RS.Classical.Deligne.SimpleScalars
import RS.Classical.Deligne.SplitAdjoint
import RS.Classical.Deligne.SplitClosure
import RS.Classical.Deligne.SplitEverything
import RS.Classical.Deligne.SplitAssemble
import RS.Classical.Deligne.SplitComplement
import RS.Classical.Deligne.SplitExact
import RS.Classical.Deligne.SplitExtract
import RS.Classical.Deligne.SplitExtractDual
import RS.Classical.Deligne.SplitMonHom
import RS.Classical.Deligne.SplitPairDef
import RS.Classical.Deligne.SplitReduce
import RS.Classical.Deligne.SplitTransport
import RS.Classical.Deligne.SplittingAlgebra
import RS.Classical.Deligne.StateTransport
import RS.Classical.Deligne.StepA
import RS.Classical.Deligne.StepATransport
import RS.Classical.Deligne.StepB
import RS.Classical.Deligne.SuperEmbed
import RS.Classical.Deligne.SuperEmbed.Letters
import RS.Classical.Deligne.SuperEmbed.Signs
import RS.Classical.Deligne.SuperEmbed.Standard
import RS.Classical.Deligne.SuperEvenRing
import RS.Classical.Deligne.SuperGamma
import RS.Classical.Deligne.SuperGammaInst
import RS.Classical.Deligne.SuperModAbelian
import RS.Classical.Deligne.SuperModBiprod
import RS.Classical.Deligne.SuperModBiprodMap
import RS.Classical.Deligne.SuperModHom
import RS.Classical.Deligne.SuperModIso
import RS.Classical.Deligne.SuperModMonoidal
import RS.Classical.Deligne.SuperModShift
import RS.Classical.Deligne.SuperModShiftUnit
import RS.Classical.Deligne.SuperModTensor
import RS.Classical.Deligne.SuperPointMod
import RS.Classical.Deligne.SuperRealize
import RS.Classical.Deligne.SuperSeries
import RS.Classical.Deligne.SuperSmall
import RS.Classical.Deligne.SuperValues
import RS.Classical.Deligne.SuperVectSchur
import RS.Classical.Deligne.SymAlg
import RS.Classical.Deligne.SymDatum
import RS.Classical.Deligne.SymMul
import RS.Classical.Deligne.TensorDatum
import RS.Classical.Deligne.TensorExact
import RS.Classical.Deligne.TensorMuBraid
import RS.Classical.Deligne.TensorPowZero
import RS.Classical.Deligne.TensorTransfer
import RS.Classical.Deligne.TensorZigzag
import RS.Classical.Deligne.TrichotomyClose
import RS.Classical.Deligne.TwistBiprod
import RS.Classical.Deligne.TwistCoherence
import RS.Classical.Deligne.TwistDatum
import RS.Classical.Deligne.TwistFreeTensor
import RS.Classical.Deligne.TwistMixLine
import RS.Classical.Deligne.TwistPow
import RS.Classical.Deligne.TwistShuffle
import RS.Classical.Deligne.TwistState
import RS.Classical.Deligne.TwistSymPow
import RS.Classical.Deligne.TwistUnitor
import RS.Classical.Deligne.UnitBase
import RS.Classical.Deligne.UnitFreeMod
import RS.Classical.Deligne.UnitMod
import RS.Classical.Deligne.UnitSimple
import RS.Classical.Deligne.UnitStage
import RS.Classical.Deligne.UniversalAlgebra
import RS.Classical.Deligne.WhiskerFaithful
import RS.Classical.Deligne.WordMap
import RS.Classical.Deligne.ZagAction
import RS.Classical.Deligne.ZigzagCarrier
import RS.Classical.Deligne.ZigzagNonzero
import RS.Classical.Deligne.ZigzagSandwich
import RS.Classical.Deligne.ZigzagTransfer
import RS.Classical.Deligne.ZigzagTransferIso

/-!
# The Deligne development: aggregator

This module imports every file of the `RS.Classical.Deligne`
development, so that a single import brings the whole of the
Deligne-theorem work into scope.  It declares nothing of its own.
-/
