import RS.Classical.Deligne.ScalarLinear

/-!
# Realization of ind-super-objects as honest super algebras

The §4 descent works with commutative algebra in genuine
ℤ/2-graded ℂ-modules.  This file supplies the bridge in three
layers.

* `RS.SuperCommAlgebra` — a super-commutative ℂ-algebra presented
  as a pair of ℂ-modules with the four graded multiplication
  blocks and the Koszul sign rule, mirroring the two-component
  design of `RS.SuperVect`.  The key lemmas: the
  ideal generated by the odd part is nil
  (`oddIdeal_le_nilradical`, `isNilpotent_of_mem_oddIdeal`), hence
  proper on a nonzero algebra (`oddIdeal_ne_top`), so the quotient
  `S.even ⧸ S.oddIdeal` is a nonzero *ordinary* commutative
  ℂ-algebra (`nontrivial_quotient_of_nontrivial`) — step (i) of
  Deligne's §4.5 ending, feeding `RS.exists_algHom_complex`.

* `RS.SuperMod` — the category of ℤ/2-graded ℂ-modules of
  arbitrary dimension: pairs of ℂ-modules with grading-preserving
  linear maps, `RS.SuperVect` with the finiteness constraints
  removed, with its additive and ℂ-linear structure.

* `RS.superRealize` — the Γ-functor.  The whole Ind-layer runs
  over a small category (`RS.indOf`, the `Ind C` instances), and
  `RS.SuperVect` is large, so the functor is stated at the tree's
  standard generality: a small preadditive `C` with finite
  colimits and a chosen generator pair `g₀ g₁ : C` (the unit and
  the odd line of a small model of `SuperVect`; `SuperSmall.lean`
  builds one).  On an
  ind-object it takes `Hom(indOf g₀, −)` and `Hom(indOf g₁, −)` as
  the even and odd parts, with ℂ-module structures from the linear
  structure of `Ind C`.  It is additive and ℂ-linear
  (`superRealize_additive`, `superRealize_linear`), and it
  reflects zero objects whenever the pair biproduct-generates `C`
  (`isZero_of_isZero_superRealize`), via the embedded-generator
  vanishing lemma `indOf_hom_eq_zero` and the recognition
  `isZero_of_generator_hom_eq_zero` of zero ind-objects by their
  values on `C`.
-/

namespace RS

/-! ## Super-commutative ℂ-algebras as graded pairs -/

universe u u' v

/-- A *super-commutative ℂ-algebra*, presented as a pair of
ℂ-modules — the even and odd components — with the four graded
multiplication blocks, associativity at every parity pattern, and
commutativity with the Koszul sign: even elements are central and
odd elements anticommute.  This is the honest algebraic shadow of
a commutative monoid object of the ind-completion of super vector
spaces. -/
-- `u` and `u'` are the universes of the even and odd components:
-- independent by design, and the structure is a pair, so they can
-- only ever occur together in its type.
@[nolint checkUnivs]
structure SuperCommAlgebra where
  /-- The even component. -/
  even : Type u
  /-- The odd component. -/
  odd : Type u'
  [evenAddCommGroup : AddCommGroup even]
  [evenModule : Module ℂ even]
  [oddAddCommGroup : AddCommGroup odd]
  [oddModule : Module ℂ odd]
  /-- The multiplicative unit, an even element. -/
  one : even
  /-- Multiplication, even times even. -/
  mulEE : even →ₗ[ℂ] even →ₗ[ℂ] even
  /-- Multiplication, even times odd. -/
  mulEO : even →ₗ[ℂ] odd →ₗ[ℂ] odd
  /-- Multiplication, odd times even. -/
  mulOE : odd →ₗ[ℂ] even →ₗ[ℂ] odd
  /-- Multiplication, odd times odd. -/
  mulOO : odd →ₗ[ℂ] odd →ₗ[ℂ] even
  /-- The unit law on the even component. -/
  one_mul_e : ∀ x, mulEE one x = x
  /-- The unit law on the odd component. -/
  one_mul_o : ∀ u, mulEO one u = u
  /-- Associativity at parity pattern even-even-even. -/
  assoc_eee : ∀ x y z, mulEE (mulEE x y) z = mulEE x (mulEE y z)
  /-- Associativity at parity pattern even-even-odd. -/
  assoc_eeo : ∀ x y u, mulEO (mulEE x y) u = mulEO x (mulEO y u)
  /-- Associativity at parity pattern even-odd-even. -/
  assoc_eoe : ∀ x u y, mulOE (mulEO x u) y = mulEO x (mulOE u y)
  /-- Associativity at parity pattern even-odd-odd. -/
  assoc_eoo : ∀ x u v, mulOO (mulEO x u) v = mulEE x (mulOO u v)
  /-- Associativity at parity pattern odd-even-even. -/
  assoc_oee : ∀ u x y, mulOE (mulOE u x) y = mulOE u (mulEE x y)
  /-- Associativity at parity pattern odd-even-odd. -/
  assoc_oeo : ∀ u x v, mulOO (mulOE u x) v = mulOO u (mulEO x v)
  /-- Associativity at parity pattern odd-odd-even. -/
  assoc_ooe : ∀ u v y, mulEE (mulOO u v) y = mulOO u (mulOE v y)
  /-- Associativity at parity pattern odd-odd-odd. -/
  assoc_ooo : ∀ u v w, mulEO (mulOO u v) w = mulOE u (mulOO v w)
  /-- Even elements commute. -/
  comm_ee : ∀ x y, mulEE x y = mulEE y x
  /-- Even and odd elements commute: the sign `(−1)^{0·1}` is
  `1`. -/
  comm_eo : ∀ x u, mulEO x u = mulOE u x
  /-- Odd elements anticommute: the Koszul sign `(−1)^{1·1}` is
  `−1`. -/
  comm_oo : ∀ u v, mulOO u v = -mulOO v u

attribute [instance] SuperCommAlgebra.evenAddCommGroup
  SuperCommAlgebra.evenModule SuperCommAlgebra.oddAddCommGroup
  SuperCommAlgebra.oddModule

namespace SuperCommAlgebra

variable (S : SuperCommAlgebra.{u, u'})

/-- In a ℂ-module an element equal to its own negative vanishes:
division by two is available in characteristic zero. -/
private theorem eq_zero_of_self_eq_neg {M : Type*} [AddCommGroup M]
    [Module ℂ M] {x : M} (h : x = -x) : x = 0 := by
  have h2 : (2 : ℂ) • x = 0 := by
    rw [two_smul]
    nth_rewrite 2 [h]
    exact add_neg_cancel x
  have hx : ((2 : ℂ)⁻¹) • ((2 : ℂ) • x) = x := by
    rw [smul_smul]
    norm_num
  rw [← hx, h2, smul_zero]

/-- The recurring cancellation `(uv)·u = 0` for odd `u`, `v`:
moving `u` across `v` and across itself produces the two opposite
signs at once. -/
theorem mulEO_mulOO_self (u v : S.odd) :
    S.mulEO (S.mulOO u v) u = 0 := by
  have ha : S.mulEO (S.mulOO u v) u = -S.mulOE u (S.mulOO u v) := by
    rw [S.assoc_ooo, S.comm_oo v u, map_neg]
  have hb : S.mulEO (S.mulOO u v) u = S.mulOE u (S.mulOO u v) :=
    S.comm_eo _ u
  have hb0 : S.mulOE u (S.mulOO u v) = 0 :=
    eq_zero_of_self_eq_neg (hb.symm.trans ha)
  exact hb.trans hb0

/-- Products of two odd elements are square-zero in the even
component. -/
theorem mulEE_mulOO_self (u v : S.odd) :
    S.mulEE (S.mulOO u v) (S.mulOO u v) = 0 := by
  rw [← S.assoc_eoo, S.mulEO_mulOO_self, map_zero,
    LinearMap.zero_apply]

/-- The even component is an ordinary commutative ring under the
even-even multiplication block. -/
instance instCommRingEven : CommRing S.even :=
  { S.evenAddCommGroup with
    mul := fun x y => S.mulEE x y
    one := S.one
    left_distrib := fun x y z => map_add (S.mulEE x) y z
    right_distrib := fun x y z => by
      show S.mulEE (x + y) z = S.mulEE x z + S.mulEE y z
      rw [map_add S.mulEE x y, LinearMap.add_apply]
    zero_mul := fun x => by
      show S.mulEE 0 x = 0
      rw [map_zero S.mulEE, LinearMap.zero_apply]
    mul_zero := fun x => map_zero (S.mulEE x)
    mul_assoc := S.assoc_eee
    one_mul := S.one_mul_e
    mul_one := fun x => (S.comm_ee x S.one).trans (S.one_mul_e x)
    mul_comm := S.comm_ee }

/-- Multiplication in the even ring is the even-even block. -/
theorem mul_def (x y : S.even) : x * y = S.mulEE x y := rfl

/-- The unit of the even ring is the structural unit. -/
theorem one_def : (1 : S.even) = S.one := rfl

/-- The even component is a ℂ-algebra: the scalar action is the
module structure, compatible with multiplication by bilinearity of
the even-even block. -/
instance instAlgebraEven : Algebra ℂ S.even :=
  Algebra.ofModule
    (fun r x y => by
      show S.mulEE (r • x) y = r • S.mulEE x y
      rw [map_smul S.mulEE r x, LinearMap.smul_apply])
    (fun r x y => map_smul (S.mulEE x) r y)

/-- The even part of the ideal generated by the odd component: the
ideal of the even ring spanned by the products of two odd
elements. -/
def oddIdeal : Ideal S.even :=
  Ideal.span (Set.range fun p : S.odd × S.odd => S.mulOO p.1 p.2)

/-- **The odd-generated ideal is nil**: it is spanned by
square-zero elements of a commutative ring, so it lies inside the
nilradical. -/
theorem oddIdeal_le_nilradical : S.oddIdeal ≤ nilradical S.even := by
  rw [oddIdeal, Ideal.span_le]
  rintro x ⟨⟨u, v⟩, rfl⟩
  exact mem_nilradical.mpr ⟨2, by
    rw [pow_two, mul_def]; exact S.mulEE_mulOO_self u v⟩

/-- Every element of the odd-generated ideal is nilpotent. -/
theorem isNilpotent_of_mem_oddIdeal {x : S.even}
    (hx : x ∈ S.oddIdeal) : IsNilpotent x :=
  mem_nilradical.mp (S.oddIdeal_le_nilradical hx)

/-- On a nonzero even ring the odd-generated ideal is proper: the
unit is not nilpotent. -/
theorem oddIdeal_ne_top [Nontrivial S.even] : S.oddIdeal ≠ ⊤ := by
  intro h
  have h1 : (1 : S.even) ∈ S.oddIdeal := h ▸ Submodule.mem_top
  obtain ⟨n, hn⟩ := S.isNilpotent_of_mem_oddIdeal h1
  rw [one_pow] at hn
  exact one_ne_zero hn

/-- Killing the odd-generated ideal of a super-commutative
ℂ-algebra with nonzero even part leaves a nonzero ordinary
commutative ℂ-algebra. -/
theorem nontrivial_quotient_oddIdeal [Nontrivial S.even] :
    Nontrivial (S.even ⧸ S.oddIdeal) :=
  Ideal.Quotient.nontrivial_iff.mpr S.oddIdeal_ne_top

/-- A trivial even component trivializes the odd component: the
unit acts as the identity on odd elements. -/
theorem subsingleton_odd (h : Subsingleton S.even) :
    Subsingleton S.odd := by
  refine subsingleton_of_forall_eq 0 fun u => ?_
  have h1 : S.one = (0 : S.even) := Subsingleton.elim _ _
  have h2 : S.mulEO S.one u = u := S.one_mul_o u
  rw [h1, map_zero, LinearMap.zero_apply] at h2
  exact h2.symm

/-- A nonzero super-commutative ℂ-algebra has nonzero even
part. -/
theorem nontrivial_even_of_nontrivial
    (h : Nontrivial S.even ∨ Nontrivial S.odd) :
    Nontrivial S.even := by
  rcases h with h | h
  · exact h
  · by_contra hc
    rw [not_nontrivial_iff_subsingleton] at hc
    exact not_subsingleton_iff_nontrivial.mpr h (S.subsingleton_odd hc)

/-- **The odd-nil quotient** (Deligne §4.5, step (i)): a nonzero
super-commutative ℂ-algebra has a nonzero *ordinary* commutative
ℂ-algebra quotient — the even part modulo the ideal generated by
the odd part.  The `CommRing` and `Algebra ℂ` structures on the
quotient are the `Ideal.Quotient` instances over
`instCommRingEven` and `instAlgebraEven`. -/
theorem nontrivial_quotient_of_nontrivial
    (h : Nontrivial S.even ∨ Nontrivial S.odd) :
    Nontrivial (S.even ⧸ S.oddIdeal) :=
  haveI := S.nontrivial_even_of_nontrivial h
  S.nontrivial_quotient_oddIdeal

end SuperCommAlgebra

/-! ## The category of ℤ/2-graded ℂ-modules -/

/-- A *super module* over ℂ: a pair of complex modules of
arbitrary dimension, the even and odd components — `RS.SuperVect`
with the finiteness constraints removed. -/
structure SuperMod where
  /-- The even-graded component. -/
  even : Type u
  /-- The odd-graded component. -/
  odd : Type u
  [evenAddCommGroup : AddCommGroup even]
  [evenModule : Module ℂ even]
  [oddAddCommGroup : AddCommGroup odd]
  [oddModule : Module ℂ odd]

attribute [instance] SuperMod.evenAddCommGroup SuperMod.evenModule
  SuperMod.oddAddCommGroup SuperMod.oddModule

namespace SuperMod

open CategoryTheory

/-- A morphism of super modules: a pair of ℂ-linear maps
preserving the grading. -/
@[ext]
structure Hom (V W : SuperMod.{u}) where
  /-- The even component of the morphism. -/
  evenMap : V.even →ₗ[ℂ] W.even
  /-- The odd component of the morphism. -/
  oddMap : V.odd →ₗ[ℂ] W.odd

/-- The identity morphism on a super module. -/
@[simp]
def Hom.id (V : SuperMod.{u}) : Hom V V where
  evenMap := LinearMap.id
  oddMap := LinearMap.id

/-- Composition of super-module morphisms. -/
@[simp]
def Hom.comp {V W X : SuperMod.{u}} (g : Hom W X) (f : Hom V W) :
    Hom V X where
  evenMap := g.evenMap.comp f.evenMap
  oddMap := g.oddMap.comp f.oddMap

/-- Super modules and grading-preserving maps form a category. -/
instance instCategoryStruct : CategoryStruct SuperMod.{u} where
  Hom := Hom
  id := Hom.id
  comp f g := Hom.comp g f

/-- Two morphisms agreeing in both components are equal. -/
@[ext]
theorem hom_ext {V W : SuperMod.{u}} {f g : V ⟶ W}
    (he : (f : Hom V W).evenMap = (g : Hom V W).evenMap)
    (ho : (f : Hom V W).oddMap = (g : Hom V W).oddMap) : f = g :=
  Hom.ext he ho

/-- SuperMod forms a category with grading-preserving linear
maps. -/
instance instCategory : Category SuperMod.{u} where
  id_comp _ := by ext <;> simp [CategoryStruct.comp, CategoryStruct.id]
  comp_id _ := by ext <;> simp [CategoryStruct.comp, CategoryStruct.id]
  assoc _ _ _ := by ext <;> simp [CategoryStruct.comp]

/-! ### Additive and linear structure, mirroring `SuperVect` -/

/-- The zero morphism: zero in both components. -/
instance {V W : SuperMod.{u}} : Zero (V ⟶ W) :=
  ⟨⟨0, 0⟩⟩

/-- Componentwise addition of morphisms. -/
instance {V W : SuperMod.{u}} : Add (V ⟶ W) :=
  ⟨fun f g => ⟨f.evenMap + g.evenMap, f.oddMap + g.oddMap⟩⟩

/-- Componentwise negation. -/
instance {V W : SuperMod.{u}} : Neg (V ⟶ W) :=
  ⟨fun f => ⟨-f.evenMap, -f.oddMap⟩⟩

/-- Componentwise subtraction. -/
instance {V W : SuperMod.{u}} : Sub (V ⟶ W) :=
  ⟨fun f g => ⟨f.evenMap - g.evenMap, f.oddMap - g.oddMap⟩⟩

/-- Componentwise scaling by a complex number. -/
instance {V W : SuperMod.{u}} : SMul ℂ (V ⟶ W) :=
  ⟨fun c f => ⟨c • f.evenMap, c • f.oddMap⟩⟩

/-- Componentwise natural scaling, definitional so that the
`AddCommGroup` structure below has no transported `nsmul`
field. -/
instance {V W : SuperMod.{u}} : SMul ℕ (V ⟶ W) :=
  ⟨fun n f => ⟨n • f.evenMap, n • f.oddMap⟩⟩

/-- Componentwise integer scaling, likewise definitional. -/
instance {V W : SuperMod.{u}} : SMul ℤ (V ⟶ W) :=
  ⟨fun n f => ⟨n • f.evenMap, n • f.oddMap⟩⟩

/-- The components of a morphism determine it; the additive and
module structures are pulled back componentwise. -/
def homComponents {V W : SuperMod.{u}} (f : V ⟶ W) :
    (V.even →ₗ[ℂ] W.even) × (V.odd →ₗ[ℂ] W.odd) :=
  (f.evenMap, f.oddMap)

/-- Componentwise equality of morphisms. -/
theorem homComponents_injective {V W : SuperMod.{u}} :
    Function.Injective (homComponents (V := V) (W := W)) :=
  fun _ _ h => Hom.ext (congrArg Prod.fst h) (congrArg Prod.snd h)

/-- Morphisms form an abelian group, pulled back along the
injection into the pair of component maps. -/
instance {V W : SuperMod.{u}} : AddCommGroup (V ⟶ W) :=
  homComponents_injective.addCommGroup homComponents
    rfl (fun _ _ => rfl) (fun _ => rfl) (fun _ _ => rfl)
    (fun _ _ => rfl) (fun _ _ => rfl)

/-- Morphisms form a ℂ-module, pulled back the same way. -/
instance {V W : SuperMod.{u}} : Module ℂ (V ⟶ W) :=
  homComponents_injective.module ℂ
    { toFun := homComponents
      map_zero' := rfl
      map_add' := fun _ _ => rfl }
    (fun _ _ => rfl)

/-- Addition of morphisms is componentwise on the even part. -/
@[simp]
theorem add_evenMap {V W : SuperMod.{u}} (f g : V ⟶ W) :
    (f + g).evenMap = f.evenMap + g.evenMap := rfl

/-- Addition of morphisms is componentwise on the odd part. -/
@[simp]
theorem add_oddMap {V W : SuperMod.{u}} (f g : V ⟶ W) :
    (f + g).oddMap = f.oddMap + g.oddMap := rfl

/-- The zero morphism's even component is zero. -/
@[simp]
theorem zero_evenMap {V W : SuperMod.{u}} :
    (0 : V ⟶ W).evenMap = 0 := rfl

/-- The zero morphism's odd component is zero. -/
@[simp]
theorem zero_oddMap {V W : SuperMod.{u}} :
    (0 : V ⟶ W).oddMap = 0 := rfl

/-- Scalar multiplication is componentwise on the even part. -/
@[simp]
theorem smul_evenMap {V W : SuperMod.{u}} (c : ℂ) (f : V ⟶ W) :
    (c • f).evenMap = c • f.evenMap := rfl

/-- Scalar multiplication is componentwise on the odd part. -/
@[simp]
theorem smul_oddMap {V W : SuperMod.{u}} (c : ℂ) (f : V ⟶ W) :
    (c • f).oddMap = c • f.oddMap := rfl

/-- SuperMod is preadditive: composition is bilinear
componentwise. -/
instance instPreadditive : Preadditive SuperMod.{u} where
  add_comp _ _ _ f f' g := by
    apply Hom.ext
    · show g.evenMap ∘ₗ (f.evenMap + f'.evenMap) = _
      exact LinearMap.comp_add _ _ _
    · show g.oddMap ∘ₗ (f.oddMap + f'.oddMap) = _
      exact LinearMap.comp_add _ _ _
  comp_add _ _ _ f g g' := by
    apply Hom.ext
    · show (g.evenMap + g'.evenMap) ∘ₗ f.evenMap = _
      exact LinearMap.add_comp _ _ _
    · show (g.oddMap + g'.oddMap) ∘ₗ f.oddMap = _
      exact LinearMap.add_comp _ _ _

/-- SuperMod is ℂ-linear: composition is ℂ-bilinear
componentwise. -/
instance instLinear : CategoryTheory.Linear ℂ SuperMod.{u} where
  smul_comp _ _ _ c f g := by
    apply Hom.ext
    · show g.evenMap ∘ₗ (c • f.evenMap) = _
      exact LinearMap.comp_smul _ _ _
    · show g.oddMap ∘ₗ (c • f.oddMap) = _
      exact LinearMap.comp_smul _ _ _
  comp_smul _ _ _ f c g := by
    apply Hom.ext
    · show (c • g.evenMap) ∘ₗ f.evenMap = _
      exact LinearMap.smul_comp _ _ _
    · show (c • g.oddMap) ∘ₗ f.oddMap = _
      exact LinearMap.smul_comp _ _ _

/-- Even elements of a zero super module vanish: the identity
morphism is the zero morphism. -/
theorem even_eq_zero_of_isZero {V : SuperMod.{u}}
    (h : Limits.IsZero V) (x : V.even) : x = 0 := by
  have h1 : 𝟙 V = (0 : V ⟶ V) := h.eq_of_src _ _
  have h2 : (𝟙 V : Hom V V).evenMap x = (0 : V ⟶ V).evenMap x :=
    congrArg (fun f => (f : Hom V V).evenMap x) h1
  exact h2

/-- Odd elements of a zero super module vanish. -/
theorem odd_eq_zero_of_isZero {V : SuperMod.{u}}
    (h : Limits.IsZero V) (x : V.odd) : x = 0 := by
  have h1 : 𝟙 V = (0 : V ⟶ V) := h.eq_of_src _ _
  have h2 : (𝟙 V : Hom V V).oddMap x = (0 : V ⟶ V).oddMap x :=
    congrArg (fun f => (f : Hom V V).oddMap x) h1
  exact h2

end SuperMod

/-! ## The Γ-functor on the ind-completion -/

noncomputable section Realize

open CategoryTheory Limits Opposite ZeroObject

attribute [local instance] HasFiniteBiproducts.of_hasFiniteCoproducts

variable {C : Type v} [SmallCategory C] [Preadditive C]
  [HasFiniteColimits C]

/-- **The realization functor** relative to a generator pair
`g₀ g₁ : C` — the unit and the odd line of the small model of
`SuperVect` in the intended instantiation.  An ind-object realizes
as the ℤ/2-graded ℂ-module of morphisms out of the embedded
generators: `Hom(indOf g₀, −)` in even degree and
`Hom(indOf g₁, −)` in odd degree, with the ℂ-module structures
given by the linear structure of `Ind C`. -/
def superRealize (g₀ g₁ : C) [Linear ℂ (Ind C)] :
    Ind C ⥤ SuperMod.{v} where
  obj F :=
    { even := indOf.obj g₀ ⟶ F
      odd := indOf.obj g₁ ⟶ F }
  map φ :=
    { evenMap := Linear.rightComp ℂ _ φ
      oddMap := Linear.rightComp ℂ _ φ }
  map_id F := by
    apply SuperMod.hom_ext <;>
      exact LinearMap.ext fun f => Category.comp_id f
  map_comp φ ψ := by
    apply SuperMod.hom_ext <;>
      exact LinearMap.ext fun f => (Category.assoc f φ ψ).symm

/-- The realization functor is additive: postcomposition
distributes over sums of morphisms of ind-objects. -/
instance superRealize_additive (g₀ g₁ : C) [Linear ℂ (Ind C)] :
    (superRealize g₀ g₁).Additive where
  map_add {F G φ ψ} := by
    apply SuperMod.hom_ext <;>
      exact LinearMap.ext fun f => Preadditive.comp_add _ _ _ f φ ψ

/-- The realization functor is ℂ-linear. -/
instance superRealize_linear (g₀ g₁ : C) [Linear ℂ (Ind C)] :
    Functor.Linear ℂ (superRealize g₀ g₁) where
  map_smul {F G φ} r := by
    apply SuperMod.hom_ext <;>
      exact LinearMap.ext fun f => Linear.comp_smul _ _ _ f r φ

/-! ### Zero reflection -/

/-- A family of objects *biproduct-generates* a category if every
object is isomorphic to a finite biproduct of members of the
family.  For the small model of `SuperVect` the two-member family
of the unit and the odd line generates in this sense. -/
def BiproductGenerates {ι : Type*} (g : ι → C) : Prop :=
  ∀ X : C, ∃ (n : ℕ) (w : Fin n → ι), Nonempty (X ≅ ⨁ (g ∘ w))

/-- Morphisms from an embedded object into an ind-object vanish
once they vanish from the embedded generators, along a biproduct
decomposition of the object: the embedding is additive, so the
biproduct decomposition of the identity transports. -/
theorem indOf_hom_eq_zero {ι : Type*} {g : ι → C} {F : Ind C}
    (hvan : ∀ (i : ι) (f : indOf.obj (g i) ⟶ F), f = 0)
    {n : ℕ} {w : Fin n → ι} {X : C} (φ : X ≅ ⨁ (g ∘ w))
    (f : indOf.obj X ⟶ F) : f = 0 := by
  haveI : (indOf (C := C)).Additive := indOf_additive
  have hdec : f = indOf.map φ.hom ≫ (indOf.map φ.inv ≫ f) := by
    rw [← Category.assoc, ← Functor.map_comp, φ.hom_inv_id,
      CategoryTheory.Functor.map_id, Category.id_comp]
  have hk : indOf.map φ.inv ≫ f = 0 := by
    have h1 : indOf.map φ.inv ≫ f =
        indOf.map (𝟙 (⨁ (g ∘ w))) ≫ (indOf.map φ.inv ≫ f) := by
      rw [CategoryTheory.Functor.map_id, Category.id_comp]
    rw [h1, ← biproduct.total, Functor.map_sum,
      Preadditive.sum_comp]
    refine Finset.sum_eq_zero fun i _ => ?_
    rw [Functor.map_comp, Category.assoc]
    have h0 : indOf.map (biproduct.ι (g ∘ w) i) ≫
        (indOf.map φ.inv ≫ f) = 0 := hvan (w i) _
    rw [h0, comp_zero]
  rw [hdec, hk, comp_zero]

/-- **Zero recognition on values**: an ind-object with no nonzero
morphism from any embedded object is zero.  The underlying
presheaf has singleton values, so it is isomorphic to the presheaf
of the embedded zero object, and full faithfulness of the
inclusion pulls the isomorphism back. -/
theorem isZero_ind_of_hom_eq_zero {F : Ind C}
    (h : ∀ (X : C) (f : indOf.obj X ⟶ F), f = 0) : IsZero F := by
  haveI : HasZeroObject C := hasZeroObject_of_hasInitial_object
  let e : ∀ (G : Ind C) (X : C),
      (indOf.obj X ⟶ G) ≃ ((Ind.inclusion C).obj G).obj (op X) :=
    fun G X =>
      (Ind.inclusion.fullyFaithful.homEquiv.trans
        ((Ind.yonedaCompInclusion.app X).homCongr
          (Iso.refl ((Ind.inclusion C).obj G)))).trans yonedaEquiv
  have hzero : IsZero (indOf.obj (0 : C)) :=
    isZero_indOf (isZero_zero C)
  have hsubF : ∀ X : C,
      Subsingleton (((Ind.inclusion C).obj F).obj (op X)) := by
    intro X
    haveI : Subsingleton (indOf.obj X ⟶ F) :=
      subsingleton_of_forall_eq 0 fun f =>
        (h X f).trans (h X 0).symm
    exact (e F X).symm.subsingleton
  have hsub0 : ∀ X : C,
      Subsingleton
        (((Ind.inclusion C).obj (indOf.obj (0 : C))).obj (op X)) := by
    intro X
    haveI : Subsingleton (indOf.obj X ⟶ indOf.obj (0 : C)) :=
      subsingleton_of_forall_eq 0 fun f => hzero.eq_of_tgt f 0
    exact (e (indOf.obj (0 : C)) X).symm.subsingleton
  have hiso : (Ind.inclusion C).obj F ≅
      (Ind.inclusion C).obj (indOf.obj (0 : C)) := by
    refine NatIso.ofComponents (fun X => ?_) (fun {X Y} k => ?_)
    · haveI : Subsingleton (((Ind.inclusion C).obj F).obj X) :=
        hsubF X.unop
      haveI : Subsingleton
          (((Ind.inclusion C).obj (indOf.obj (0 : C))).obj X) :=
        hsub0 X.unop
      exact Equiv.toIso (equivOfSubsingletonOfSubsingleton
        (fun _ => e (indOf.obj (0 : C)) X.unop 0)
        (fun _ => e F X.unop 0))
    · haveI : Subsingleton
          (((Ind.inclusion C).obj (indOf.obj (0 : C))).obj Y) :=
        hsub0 Y.unop
      haveI : Subsingleton (((Ind.inclusion C).obj F).obj X ⟶
          ((Ind.inclusion C).obj (indOf.obj (0 : C))).obj Y) :=
        ⟨fun p q => by
          ext x
          exact Subsingleton.elim _ _⟩
      exact Subsingleton.elim _ _
  exact hzero.of_iso (Ind.inclusion.fullyFaithful.preimageIso hiso)

/-- **Zero recognition by generators**: an ind-object with no
nonzero morphism from the embedded members of a
biproduct-generating family is zero. -/
theorem isZero_of_generator_hom_eq_zero {ι : Type*} {g : ι → C}
    (hgen : BiproductGenerates g) {F : Ind C}
    (hvan : ∀ (i : ι) (f : indOf.obj (g i) ⟶ F), f = 0) :
    IsZero F := by
  refine isZero_ind_of_hom_eq_zero fun X f => ?_
  obtain ⟨n, w, ⟨φ⟩⟩ := hgen X
  exact indOf_hom_eq_zero hvan φ f

/-- The generator pair of the realization functor as a
`Bool`-indexed family: `false` is the even generator, `true` the
odd one. -/
def generatorPair (g₀ g₁ : C) : Bool → C :=
  fun b => bif b then g₁ else g₀

/-- **The realization functor reflects zero objects**: over a
biproduct-generating pair, an ind-object whose even and odd
realizations vanish is zero. -/
theorem isZero_of_isZero_superRealize (g₀ g₁ : C)
    [Linear ℂ (Ind C)]
    (hgen : BiproductGenerates (generatorPair g₀ g₁))
    {F : Ind C}
    (hF : IsZero ((superRealize g₀ g₁).obj F)) : IsZero F := by
  refine isZero_of_generator_hom_eq_zero hgen fun b => ?_
  cases b
  · exact fun f => SuperMod.even_eq_zero_of_isZero hF f
  · exact fun f => SuperMod.odd_eq_zero_of_isZero hF f

end Realize

/-! ## The convolution algebra of a commutative monoid object

The even half of the monoid transport: for a commutative monoid
object `R` of a braided ℂ-linear monoidal category — `Ind C` with
its transported structure in the intended instantiation — the
morphisms `𝟙 ⟶ R` carry an ordinary commutative ℂ-algebra
structure under the convolution product
`a · b = λ⁻¹ ≫ (a ⊗ b) ≫ μ`.  Together with the unit
identification `indOfUnitIso` this equips the even part of
`superRealize` on a commutative monoid object with its ring
structure. -/

section HomAlgebra

open CategoryTheory MonoidalCategory MonObj
open scoped MonObj

variable {D : Type u} [Category.{u'} D] [MonoidalCategory D]

/-- The convolution product of morphisms from the unit into a
monoid object. -/
noncomputable def unitHomMul (R : D) [MonObj R]
    (a b : 𝟙_ D ⟶ R) : 𝟙_ D ⟶ R :=
  (λ_ (𝟙_ D)).inv ≫ (a ⊗ₘ b) ≫ μ

variable (R : D) [MonObj R]

/-- The monoid unit is a left unit for convolution. -/
theorem one_unitHomMul (a : 𝟙_ D ⟶ R) : unitHomMul R η a = a := by
  rw [unitHomMul, MonObj.one_mul_hom, Iso.inv_hom_id_assoc]

/-- The monoid unit is a right unit for convolution. -/
theorem unitHomMul_one (a : 𝟙_ D ⟶ R) : unitHomMul R a η = a := by
  rw [unitHomMul, MonObj.mul_one_hom, ← unitors_equal,
    Iso.inv_hom_id_assoc]

/-- Convolution is associative. -/
theorem unitHomMul_assoc (a b c : 𝟙_ D ⟶ R) :
    unitHomMul R (unitHomMul R a b) c =
      unitHomMul R a (unitHomMul R b c) := by
  have key : μ[R] ≫ (ρ_ R).inv ≫ R ◁ c ≫ μ[R] =
      (ρ_ (R ⊗ R)).inv ≫ (α_ R R (𝟙_ D)).hom ≫
        R ◁ R ◁ c ≫ R ◁ μ[R] ≫ μ[R] := by
    rw [rightUnitor_inv_naturality_assoc, ← whisker_exchange_assoc,
      MonObj.mul_assoc, associator_naturality_right_assoc]
  simp [unitHomMul, tensorHom_def]
  rw [← unitors_equal]
  simp only [Iso.inv_hom_id_assoc]
  rw [key]

/-- Convolution against a commutative monoid object is
commutative. -/
theorem unitHomMul_comm [BraidedCategory D] [IsCommMonObj R]
    (a b : 𝟙_ D ⟶ R) : unitHomMul R a b = unitHomMul R b a := by
  have h : (a ⊗ₘ b) ≫ μ[R] =
      (β_ (𝟙_ D) (𝟙_ D)).hom ≫ (b ⊗ₘ a) ≫ μ[R] := by
    conv_lhs => rw [← IsCommMonObj.mul_comm R]
    rw [BraidedCategory.braiding_naturality_assoc]
  rw [unitHomMul, unitHomMul, h, braiding_tensorUnit_left]
  simp [← unitors_inv_equal]

section Bilinear

variable [Preadditive D] [MonoidalPreadditive D]

/-- Convolution is additive on the left. -/
theorem add_unitHomMul (a a' b : 𝟙_ D ⟶ R) :
    unitHomMul R (a + a') b = unitHomMul R a b + unitHomMul R a' b := by
  rw [unitHomMul, unitHomMul, unitHomMul,
    MonoidalPreadditive.add_tensor, Preadditive.add_comp,
    Preadditive.comp_add]

/-- Convolution is additive on the right. -/
theorem unitHomMul_add (a b b' : 𝟙_ D ⟶ R) :
    unitHomMul R a (b + b') = unitHomMul R a b + unitHomMul R a b' := by
  rw [unitHomMul, unitHomMul, unitHomMul,
    MonoidalPreadditive.tensor_add, Preadditive.add_comp,
    Preadditive.comp_add]

/-- Convolution kills zero on the left. -/
theorem zero_unitHomMul (b : 𝟙_ D ⟶ R) : unitHomMul R 0 b = 0 := by
  simp [unitHomMul]

/-- Convolution kills zero on the right. -/
theorem unitHomMul_zero (a : 𝟙_ D ⟶ R) : unitHomMul R a 0 = 0 := by
  simp [unitHomMul]

/-- Convolution is ℂ-homogeneous on the left. -/
theorem smul_unitHomMul [Linear ℂ D] [MonoidalLinear ℂ D] (r : ℂ)
    (a b : 𝟙_ D ⟶ R) :
    unitHomMul R (r • a) b = r • unitHomMul R a b := by
  have h : (r • a) ⊗ₘ b = r • (a ⊗ₘ b) := by
    rw [tensorHom_def, tensorHom_def,
      MonoidalLinear.smul_whiskerRight, Linear.smul_comp]
  rw [unitHomMul, unitHomMul, h, Linear.smul_comp, Linear.comp_smul]

/-- Convolution is ℂ-homogeneous on the right. -/
theorem unitHomMul_smul [Linear ℂ D] [MonoidalLinear ℂ D] (r : ℂ)
    (a b : 𝟙_ D ⟶ R) :
    unitHomMul R a (r • b) = r • unitHomMul R a b := by
  have h : a ⊗ₘ (r • b) = r • (a ⊗ₘ b) := by
    rw [tensorHom_def', tensorHom_def',
      MonoidalLinear.whiskerLeft_smul, Linear.smul_comp]
  rw [unitHomMul, unitHomMul, h, Linear.smul_comp, Linear.comp_smul]

/-- **The convolution ring**: for a commutative monoid object of a
braided preadditive monoidal category the morphisms from the unit
form a commutative ring under convolution.  Deliberately a
definition rather than an instance: at `R = 𝟙` the type coincides
with `End (𝟙_ D)`, whose composition monoid is a distinct (if
Eckmann–Hilton-equal) multiplication. -/
@[reducible] noncomputable def unitHomCommRing [BraidedCategory D]
    [IsCommMonObj R] : CommRing (𝟙_ D ⟶ R) :=
  { (inferInstance : AddCommGroup (𝟙_ D ⟶ R)) with
    mul := unitHomMul R
    one := η
    left_distrib := unitHomMul_add R
    right_distrib := add_unitHomMul R
    zero_mul := zero_unitHomMul R
    mul_zero := unitHomMul_zero R
    mul_assoc := unitHomMul_assoc R
    one_mul := one_unitHomMul R
    mul_one := unitHomMul_one R
    mul_comm := unitHomMul_comm R }

/-- **The convolution ℂ-algebra**: with ℂ-linear structure the
convolution ring of a commutative monoid object is a commutative
ℂ-algebra — the even Γ-algebra of the monoid transport once the
unit of `Ind C` is identified with the embedded even generator
(`indOfUnitIso`). -/
@[reducible] noncomputable def unitHomAlgebra [BraidedCategory D]
    [Linear ℂ D] [MonoidalLinear ℂ D] [IsCommMonObj R] :
    letI := unitHomCommRing R
    Algebra ℂ (𝟙_ D ⟶ R) :=
  letI := unitHomCommRing R
  @Algebra.ofModule ℂ (𝟙_ D ⟶ R) _ _ (Linear.homModule _ _)
    (smul_unitHomMul R) (unitHomMul_smul R)

end Bilinear

end HomAlgebra

end RS
