import RS.Classical.Deligne.UnitFreeMod
import RS.Classical.Deligne.TwistFreeTensor
import RS.Classical.Deligne.ZigzagTransferIso
import RS.Classical.Deligne.TensorZigzag
import RS.Classical.Deligne.BaseChangeTransport
import RS.Classical.Deligne.InitDatum
import RS.Classical.Deligne.OddLinePairing
import RS.Classical.Deligne.BigTensor

/-!
# The odd twist of a duality datum

A self-dual object of the ambient category makes the free module
it generates self-dual over any commutative base: the duality
datum over the trivial base is carried onto the free module and
then base-changed, and both steps preserve the zigzag laws.  For
an odd line the self-duality is the square trivialisation, so
tensoring a duality datum with the line datum and transporting
along the twist shuffle gives the odd twist of a duality datum,
zigzag laws included.
-/

namespace RS

open CategoryTheory MonoidalCategory Limits
open scoped MonObj

universe v u

variable {D : Type u} [Category.{v} D] [MonoidalCategory D]
  [SymmetricCategory D]
variable [Preadditive D] [MonoidalPreadditive D]
  [HasFiniteBiproducts D] [HasCoequalizers D]
variable [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair
  (tensorLeft Z)]
variable [∀ Z : D, PreservesColimitsOfShape WalkingParallelPair
  (tensorRight Z)]
variable (A : D) [MonObj A] [IsCommMonObj A]

section SelfDual

variable (V : D) [ExactPairing V V]

/-- The self-duality datum over the trivial base, carried onto
the free module of the trivial base. -/
noncomputable def unitFreeDatum :
    ModDualityDatum (𝟙_ D) (freeMod (𝟙_ D) V)
      (freeMod (𝟙_ D) V) :=
  (unitBaseDatum V V).transferIso (𝟙_ D)
    (unitFreeIso V).symm (unitFreeIso V).symm

/-- The carried datum satisfies the zigzag laws. -/
theorem unitFreeDatum_zigzag :
    ModZigzagDatum (𝟙_ D) (unitFreeDatum V) :=
  modZigzagDatum_transferIso (𝟙_ D) (unitBaseDatum V V)
    (unitFreeIso V).symm (unitFreeIso V).symm
    (unitBaseDatum_zigzag V V)

/-- **The free module on a self-dual object is self-dual** over
any commutative base. -/
noncomputable def freeSelfDatum :
    ModDualityDatum A (freeMod A V) (freeMod A V) :=
  (baseChangeDatum (𝟙_ D) A η[A] (unitFreeDatum V)).transferIso A
    (baseChangeFreeIso (𝟙_ D) A η[A] V).symm
    (baseChangeFreeIso (𝟙_ D) A η[A] V).symm

/-- The free self-duality datum satisfies the zigzag laws. -/
theorem freeSelfDatum_zigzag :
    ModZigzagDatum A (freeSelfDatum A V) :=
  modZigzagDatum_transferIso A
    (baseChangeDatum (𝟙_ D) A η[A] (unitFreeDatum V))
    (baseChangeFreeIso (𝟙_ D) A η[A] V).symm
    (baseChangeFreeIso (𝟙_ D) A η[A] V).symm
    (baseChangeZigzag D (𝟙_ D) _ _ (freeMod (𝟙_ D) V)
      (freeMod (𝟙_ D) V) (unitFreeDatum V)
      (unitFreeDatum_zigzag V) A _ _ η[A] _)

end SelfDual

section Twist

variable (L : OddLine D)

/-- **The line datum**: the module generated by the odd line is
self-dual over any commutative base. -/
noncomputable def lineDatum :
    ModDualityDatum A (freeMod A L.obj) (freeMod A L.obj) :=
  letI := L.exactPairing
  freeSelfDatum A L.obj

/-- The line datum satisfies the zigzag laws. -/
theorem lineDatum_zigzag : ModZigzagDatum A (lineDatum A L) :=
  letI := L.exactPairing
  freeSelfDatum_zigzag A L.obj

variable {M M' : Mod D A}

/-- **The odd twist of a duality datum**: tensor with the line
datum and transport along the twist shuffle. -/
noncomputable def twistDatum (d : ModDualityDatum A M M') :
    ModDualityDatum A (tensorLeftMod A L.obj M)
      (tensorLeftMod A L.obj M') :=
  (tensorDatum A (lineDatum A L) d).transferIso A
    (freeTensorTwistIso A L.obj M).symm
    (freeTensorTwistIso A L.obj M').symm

/-- **The odd twist preserves the zigzag laws.** -/
theorem twistDatum_zigzag (d : ModDualityDatum A M M')
    (hz : ModZigzagDatum A d) :
    ModZigzagDatum A (twistDatum A L d) :=
  modZigzagDatum_transferIso A (tensorDatum A (lineDatum A L) d)
    (freeTensorTwistIso A L.obj M).symm
    (freeTensorTwistIso A L.obj M').symm
    (tensorDatum_zigzag A (lineDatum A L) d
      (lineDatum_zigzag A L) hz)

end Twist

end RS
