import RS.Classical.Deligne.PointMonoidal.Residue

/-!
# The comparison in super vector spaces, and its inverse

The tensor product of two super vector spaces is the graded tensor
product of the components, while the tensor product of two super
modules is its quotient by the balancing relations; the quotient
map is the second half of the comparison, and composing it with the
comparison over the algebra of [Residue.lean](Residue.lean) gives
the comparison `RS.superVectMu` of the fibre functor.

The inverse is built here as well: the residue module is generated
in even degree by the image of the unit, so
`(m ⊗ n) ⊗ a ↦ (m ⊗ a) ⊗ (n ⊗ 1)` is well defined — an even scalar
crosses either factor as its value at the point, and an odd scalar
kills both sides.  That the two composites are the identity is
proved in [Coherence.lean](Coherence.lean); no freeness and no rank
hypothesis is needed.

## Contents

* `RS.pointOne`, `RS.pointScale`: the unit of the residue module
  and the scaling it induces, with the four generator identities
  `RS.tmulEE_actEE_pointOne` and companions.
* `RS.gradedTensorEven`, `RS.gradedTensorOdd`: the quotient maps
  from the graded tensor product of the components, with their
  surjectivity and their naturality.
* `RS.baseNuEven`, `RS.baseNuOdd`: the inverse comparison, built
  from the four balanced blocks `RS.baseNuFee` and companions
  through an inner and an outer lift.
* `RS.superVectMuEvenRaw`, `RS.superVectMuOddRaw`: the comparison
  before the coordinates are installed.
* `RS.superVectMu`: the comparison of the fibre functor, in
  `RS.SuperVect`, with the four generator formulas
  `RS.superVectMu_evenMap_ee` and companions.
* `RS.svEvenInl` and its three companions: the four summands of a
  tensor product of super vector spaces.
-/

namespace RS

open CategoryTheory MonoidalCategory
open SuperCommAlgebra (pointMod)
open SuperCommAlgebra.Mod

universe u

/-! ## The inverse comparison

The residue module is generated in even degree by the image of the
unit, so the base change of a module is generated by the products
`m ⊗ 1`, and the map that sends `(m ⊗ n) ⊗ a` to
`(m ⊗ a) ⊗ (n ⊗ 1)` is well defined: an even scalar passes across
either factor as its value at the point, and an odd scalar kills
both sides. -/

section Inverse

open scoped TensorProduct

variable {S : SuperCommAlgebra.{u, u}} (P : SuperPoint S)

/-- The unit of the residue module. -/
noncomputable def pointOne : (pointMod P : S.Mod.{u, u, u, u}).even :=
  ULift.up 1

/-- **Scaling by a residue class**: a residue class acts on any
complex vector space by its underlying complex number.  The residue
module being one dimensional in even degree, this describes every
linear map out of it. -/
noncomputable def pointScale (X : Type u) [AddCommGroup X]
    [Module ℂ X] :
    X →ₗ[ℂ] ((pointMod P : S.Mod.{u, u, u, u}).even →ₗ[ℂ] X) where
  toFun x := LinearMap.smulRight
    (ULift.moduleEquiv (R := ℂ) (M := ℂ)).toLinearMap x
  map_add' x y := LinearMap.ext fun a => by
    show a.down • (x + y) = a.down • x + a.down • y
    exact smul_add _ _ _
  map_smul' c x := LinearMap.ext fun a => by
    show a.down • (c • x) = c • (a.down • x)
    rw [smul_comm]

/-- Scaling by a residue class, evaluated. -/
@[simp] theorem pointScale_apply (X : Type u) [AddCommGroup X]
    [Module ℂ X] (x : X)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    pointScale P X x a = a.down • x := rfl

variable (M : S.Mod.{u, u, u, u})

/-- An even scalar crosses an even product with the unit as its
value at the point. -/
theorem tmulEE_actEE_pointOne (b : S.even) (m : M.even) :
    tmulEE M (pointMod P) (M.actEE b m) (pointOne P) =
      P.chi b • tmulEE M (pointMod P) m (pointOne P) := by
  rw [tmulEE_balanced_eee]
  have h : (pointMod P : S.Mod.{u, u, u, u}).actEE b (pointOne P)
      = P.chi b • pointOne P := ULift.ext _ _ (by
    show P.chi b * 1 = P.chi b * 1
    rfl)
  rw [h, map_smul]

/-- An even scalar crosses an odd product with the unit as its
value at the point. -/
theorem tmulOE_actEO_pointOne (b : S.even) (m : M.odd) :
    tmulOE M (pointMod P) (M.actEO b m) (pointOne P) =
      P.chi b • tmulOE M (pointMod P) m (pointOne P) := by
  rw [tmulOE_balanced_eoe]
  have h : (pointMod P : S.Mod.{u, u, u, u}).actEE b (pointOne P)
      = P.chi b • pointOne P := ULift.ext _ _ (by
    show P.chi b * 1 = P.chi b * 1
    rfl)
  rw [h, map_smul]

/-- An odd scalar kills the even products with the unit. -/
theorem tmulEE_actOO_pointOne (c : S.odd) (m : M.odd) :
    tmulEE M (pointMod P) (M.actOO c m) (pointOne P) = 0 := by
  rw [tmulEE_balanced_ooe, pointMod_actOE, map_zero, neg_zero]

/-- An odd scalar kills the odd products with the unit. -/
theorem tmulOE_actOE_pointOne (c : S.odd) (m : M.even) :
    tmulOE M (pointMod P) (M.actOE c m) (pointOne P) = 0 := by
  rw [tmulOE_balanced_oee, pointMod_actOE, map_zero]

end Inverse

/-! ## The comparison of the graded tensor product

The even part of the tensor product of two super modules is a
quotient of the graded tensor product of their components, and
likewise in odd degree.  The quotient maps are the comparison
between the tensor product of super vector spaces — which is the
graded tensor product of the components — and the tensor product
of super modules. -/

section GradedComparison

variable {S : SuperCommAlgebra.{u, u}} (A B : S.Mod.{u, u, u, u})

open scoped TensorProduct

/-- **The graded comparison in even degree**: the quotient map
onto the even part of the tensor product. -/
noncomputable def gradedTensorEven :
    (A.even ⊗[ℂ] B.even) × (A.odd ⊗[ℂ] B.odd) →ₗ[ℂ]
      (A.tensor B : S.Mod.{u, u, u, u}).even :=
  (balEven A B).mkQ

/-- **The graded comparison in odd degree**: the quotient map onto
the odd part of the tensor product. -/
noncomputable def gradedTensorOdd :
    (A.even ⊗[ℂ] B.odd) × (A.odd ⊗[ℂ] B.even) →ₗ[ℂ]
      (A.tensor B : S.Mod.{u, u, u, u}).odd :=
  (balOdd A B).mkQ

/-- The even comparison on an even-even product. -/
@[simp] theorem gradedTensorEven_ee (a : A.even) (b : B.even) :
    gradedTensorEven A B (a ⊗ₜ[ℂ] b, 0) = tmulEE A B a b := rfl

/-- The even comparison on an odd-odd product. -/
@[simp] theorem gradedTensorEven_oo (a : A.odd) (b : B.odd) :
    gradedTensorEven A B (0, a ⊗ₜ[ℂ] b) = tmulOO A B a b := rfl

/-- The odd comparison on an even-odd product. -/
@[simp] theorem gradedTensorOdd_eo (a : A.even) (b : B.odd) :
    gradedTensorOdd A B (a ⊗ₜ[ℂ] b, 0) = tmulEO A B a b := rfl

/-- The odd comparison on an odd-even product. -/
@[simp] theorem gradedTensorOdd_oe (a : A.odd) (b : B.even) :
    gradedTensorOdd A B (0, a ⊗ₜ[ℂ] b) = tmulOE A B a b := rfl

/-- **The graded comparison is natural**: the quotient maps
commute with the tensor product of two morphisms. -/
theorem gradedTensorEven_naturality {A' B' : S.Mod.{u, u, u, u}}
    (uu : A ⟶ A') (vv : B ⟶ B') :
    (SuperCommAlgebra.Mod.tensorHom uu vv).evenMap.comp
        (gradedTensorEven A B) =
      (gradedTensorEven A' B').comp
        (LinearMap.prodMap
          (TensorProduct.map uu.evenMap vv.evenMap)
          (TensorProduct.map uu.oddMap vv.oddMap)) := by
  refine LinearMap.prod_ext (TensorProduct.ext' fun x y => ?_)
    (TensorProduct.ext' fun x y => ?_)
  · show (SuperCommAlgebra.Mod.tensorHom uu vv).evenMap
      (tmulEE A B x y) = _
    rw [tensorHom_evenMap_tmulEE]
    rfl
  · show (SuperCommAlgebra.Mod.tensorHom uu vv).evenMap
      (tmulOO A B x y) = _
    rw [tensorHom_evenMap_tmulOO]
    rfl

/-- **The graded comparison is natural**, in odd degree. -/
theorem gradedTensorOdd_naturality {A' B' : S.Mod.{u, u, u, u}}
    (uu : A ⟶ A') (vv : B ⟶ B') :
    (SuperCommAlgebra.Mod.tensorHom uu vv).oddMap.comp
        (gradedTensorOdd A B) =
      (gradedTensorOdd A' B').comp
        (LinearMap.prodMap
          (TensorProduct.map uu.evenMap vv.oddMap)
          (TensorProduct.map uu.oddMap vv.evenMap)) := by
  refine LinearMap.prod_ext (TensorProduct.ext' fun x y => ?_)
    (TensorProduct.ext' fun x y => ?_)
  · show (SuperCommAlgebra.Mod.tensorHom uu vv).oddMap
      (tmulEO A B x y) = _
    rw [tensorHom_oddMap_tmulEO]
    rfl
  · show (SuperCommAlgebra.Mod.tensorHom uu vv).oddMap
      (tmulOE A B x y) = _
    rw [tensorHom_oddMap_tmulOE]
    rfl

end GradedComparison

/-! ## The inverse of the comparison

The comparison morphism is invertible: base change along a point
is strong monoidal, not merely lax.  The inverse sends
`(m ⊗ n) ⊗ a` to `(m ⊗ a) ⊗ (n ⊗ 1)`; it is well defined because an
even scalar crosses both factors as its value at the point and an
odd scalar kills both sides. -/

section InverseMap

open scoped TensorProduct

variable {S : SuperCommAlgebra.{u, u}} (P : SuperPoint S)
  (M N : S.Mod.{u, u, u, u})

/-- The even part of the graded tensor product of the two base
changes: the codomain of the inverse comparison in even degree. -/
abbrev basePairEven : Type u :=
  ((M.tensor (pointMod P)).even ⊗[ℂ]
      (N.tensor (pointMod P)).even) ×
    ((M.tensor (pointMod P)).odd ⊗[ℂ]
      (N.tensor (pointMod P)).odd)

/-- The odd part of the graded tensor product of the two base
changes. -/
abbrev basePairOdd : Type u :=
  ((M.tensor (pointMod P)).even ⊗[ℂ]
      (N.tensor (pointMod P)).odd) ×
    ((M.tensor (pointMod P)).odd ⊗[ℂ]
      (N.tensor (pointMod P)).even)

/-- The even-even block of the inverse comparison. -/
noncomputable def baseNuFee :
    M.even →ₗ[ℂ] N.even →ₗ[ℂ]
      ((pointMod P : S.Mod.{u, u, u, u}).even →ₗ[ℂ]
        basePairEven P M N) :=
  LinearMap.compr₂
    (LinearMap.compl₁₂
      (LinearMap.compr₂ (TensorProduct.mk ℂ
          (M.tensor (pointMod P)).even
          (N.tensor (pointMod P)).even) (LinearMap.inl ℂ _ _))
      ((tmulEE M (pointMod P)).flip (pointOne P))
      ((tmulEE N (pointMod P)).flip (pointOne P)))
    (pointScale P (basePairEven P M N))

/-- The odd-odd block of the inverse comparison. -/
noncomputable def baseNuFoo :
    M.odd →ₗ[ℂ] N.odd →ₗ[ℂ]
      ((pointMod P : S.Mod.{u, u, u, u}).even →ₗ[ℂ]
        basePairEven P M N) :=
  LinearMap.compr₂
    (LinearMap.compl₁₂
      (LinearMap.compr₂ (TensorProduct.mk ℂ
          (M.tensor (pointMod P)).odd
          (N.tensor (pointMod P)).odd) (LinearMap.inr ℂ _ _))
      ((tmulOE M (pointMod P)).flip (pointOne P))
      ((tmulOE N (pointMod P)).flip (pointOne P)))
    (pointScale P (basePairEven P M N))

/-- The even-odd block of the inverse comparison. -/
noncomputable def baseNuFeo :
    M.even →ₗ[ℂ] N.odd →ₗ[ℂ]
      ((pointMod P : S.Mod.{u, u, u, u}).even →ₗ[ℂ]
        basePairOdd P M N) :=
  LinearMap.compr₂
    (LinearMap.compl₁₂
      (LinearMap.compr₂ (TensorProduct.mk ℂ
          (M.tensor (pointMod P)).even
          (N.tensor (pointMod P)).odd) (LinearMap.inl ℂ _ _))
      ((tmulEE M (pointMod P)).flip (pointOne P))
      ((tmulOE N (pointMod P)).flip (pointOne P)))
    (pointScale P (basePairOdd P M N))

/-- The odd-even block of the inverse comparison. -/
noncomputable def baseNuFoe :
    M.odd →ₗ[ℂ] N.even →ₗ[ℂ]
      ((pointMod P : S.Mod.{u, u, u, u}).even →ₗ[ℂ]
        basePairOdd P M N) :=
  LinearMap.compr₂
    (LinearMap.compl₁₂
      (LinearMap.compr₂ (TensorProduct.mk ℂ
          (M.tensor (pointMod P)).odd
          (N.tensor (pointMod P)).even) (LinearMap.inr ℂ _ _))
      ((tmulOE M (pointMod P)).flip (pointOne P))
      ((tmulEE N (pointMod P)).flip (pointOne P)))
    (pointScale P (basePairOdd P M N))

variable {M N}

/-- The even-even block, evaluated. -/
@[simp] theorem baseNuFee_apply (m : M.even) (n : N.even)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    baseNuFee P M N m n a =
      a.down • (tmulEE M (pointMod P) m (pointOne P) ⊗ₜ[ℂ]
        tmulEE N (pointMod P) n (pointOne P), 0) := rfl

/-- The odd-odd block, evaluated. -/
@[simp] theorem baseNuFoo_apply (m : M.odd) (n : N.odd)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    baseNuFoo P M N m n a =
      a.down • (0, tmulOE M (pointMod P) m (pointOne P) ⊗ₜ[ℂ]
        tmulOE N (pointMod P) n (pointOne P)) := rfl

/-- The even-odd block, evaluated. -/
@[simp] theorem baseNuFeo_apply (m : M.even) (n : N.odd)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    baseNuFeo P M N m n a =
      a.down • (tmulEE M (pointMod P) m (pointOne P) ⊗ₜ[ℂ]
        tmulOE N (pointMod P) n (pointOne P), 0) := rfl

/-- The odd-even block, evaluated. -/
@[simp] theorem baseNuFoe_apply (m : M.odd) (n : N.even)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    baseNuFoe P M N m n a =
      a.down • (0, tmulOE M (pointMod P) m (pointOne P) ⊗ₜ[ℂ]
        tmulEE N (pointMod P) n (pointOne P)) := rfl

/-! ### The inner lift of the inverse comparison -/

/-- Balancing of the even-even block against an even scalar. -/
theorem baseNuFee_balanced_eee (b : S.even) (m : M.even)
    (n : N.even) :
    baseNuFee P M N (M.actEE b m) n =
      baseNuFee P M N m (N.actEE b n) := by
  refine LinearMap.ext fun a => ?_
  rw [baseNuFee_apply, baseNuFee_apply, tmulEE_actEE_pointOne,
    tmulEE_actEE_pointOne, TensorProduct.smul_tmul]

/-- Balancing of the odd-odd block against an even scalar. -/
theorem baseNuFoo_balanced_eoo (b : S.even) (m : M.odd)
    (n : N.odd) :
    baseNuFoo P M N (M.actEO b m) n =
      baseNuFoo P M N m (N.actEO b n) := by
  refine LinearMap.ext fun a => ?_
  rw [baseNuFoo_apply, baseNuFoo_apply, tmulOE_actEO_pointOne,
    tmulOE_actEO_pointOne, TensorProduct.smul_tmul]

/-- Balancing of the blocks against an odd scalar, even-odd. -/
theorem baseNuFoo_balanced_oeo (c : S.odd) (m : M.even)
    (n : N.odd) :
    baseNuFoo P M N (M.actOE c m) n =
      baseNuFee P M N m (N.actOO c n) := by
  refine LinearMap.ext fun a => ?_
  rw [baseNuFoo_apply, baseNuFee_apply, tmulOE_actOE_pointOne,
    tmulEE_actOO_pointOne, TensorProduct.zero_tmul,
    TensorProduct.tmul_zero]

/-- Balancing of the blocks against an odd scalar, odd-even. -/
theorem baseNuFee_balanced_ooe (c : S.odd) (m : M.odd)
    (n : N.even) :
    baseNuFee P M N (M.actOO c m) n =
      -baseNuFoo P M N m (N.actOE c n) := by
  refine LinearMap.ext fun a => ?_
  rw [LinearMap.neg_apply, baseNuFee_apply, baseNuFoo_apply,
    tmulEE_actOO_pointOne, tmulOE_actOE_pointOne,
    TensorProduct.zero_tmul, TensorProduct.tmul_zero]
  simp

/-- Balancing of the even-odd block against an even scalar. -/
theorem baseNuFeo_balanced_eeo (b : S.even) (m : M.even)
    (n : N.odd) :
    baseNuFeo P M N (M.actEE b m) n =
      baseNuFeo P M N m (N.actEO b n) := by
  refine LinearMap.ext fun a => ?_
  rw [baseNuFeo_apply, baseNuFeo_apply, tmulEE_actEE_pointOne,
    tmulOE_actEO_pointOne, TensorProduct.smul_tmul]

/-- Balancing of the odd-even block against an even scalar. -/
theorem baseNuFoe_balanced_eoe (b : S.even) (m : M.odd)
    (n : N.even) :
    baseNuFoe P M N (M.actEO b m) n =
      baseNuFoe P M N m (N.actEE b n) := by
  refine LinearMap.ext fun a => ?_
  rw [baseNuFoe_apply, baseNuFoe_apply, tmulOE_actEO_pointOne,
    tmulEE_actEE_pointOne, TensorProduct.smul_tmul]

/-- Balancing of the odd blocks against an odd scalar,
even-even. -/
theorem baseNuFoe_balanced_oee (c : S.odd) (m : M.even)
    (n : N.even) :
    baseNuFoe P M N (M.actOE c m) n =
      baseNuFeo P M N m (N.actOE c n) := by
  refine LinearMap.ext fun a => ?_
  rw [baseNuFoe_apply, baseNuFeo_apply, tmulOE_actOE_pointOne,
    tmulOE_actOE_pointOne, TensorProduct.zero_tmul,
    TensorProduct.tmul_zero]

/-- Balancing of the odd blocks against an odd scalar, odd-odd. -/
theorem baseNuFeo_balanced_ooo (c : S.odd) (m : M.odd)
    (n : N.odd) :
    baseNuFeo P M N (M.actOO c m) n =
      -baseNuFoe P M N m (N.actOO c n) := by
  refine LinearMap.ext fun a => ?_
  rw [LinearMap.neg_apply, baseNuFeo_apply, baseNuFoe_apply,
    tmulEE_actOO_pointOne, tmulEE_actOO_pointOne,
    TensorProduct.zero_tmul, TensorProduct.tmul_zero]
  simp

variable (M N)

/-- **The inner lift of the inverse comparison**, in even degree:
the two even blocks descend to the tensor product of the two
modules. -/
noncomputable def baseNuInnerEven :
    (M.tensor N : S.Mod.{u, u, u, u}).even →ₗ[ℂ]
      ((pointMod P : S.Mod.{u, u, u, u}).even →ₗ[ℂ]
        basePairEven P M N) :=
  liftEven M N (baseNuFee P M N) (baseNuFoo P M N)
    (baseNuFee_balanced_eee P) (baseNuFoo_balanced_eoo P)
    (baseNuFoo_balanced_oeo P) (baseNuFee_balanced_ooe P)

/-- **The inner lift of the inverse comparison**, in odd degree. -/
noncomputable def baseNuInnerOdd :
    (M.tensor N : S.Mod.{u, u, u, u}).odd →ₗ[ℂ]
      ((pointMod P : S.Mod.{u, u, u, u}).even →ₗ[ℂ]
        basePairOdd P M N) :=
  liftOdd M N (baseNuFeo P M N) (baseNuFoe P M N)
    (baseNuFeo_balanced_eeo P) (baseNuFoe_balanced_eoe P)
    (baseNuFoe_balanced_oee P) (baseNuFeo_balanced_ooo P)

variable {M N}

/-- The inner lift on even-even products. -/
@[simp] theorem baseNuInnerEven_tmulEE (m : M.even) (n : N.even) :
    baseNuInnerEven P M N (tmulEE M N m n) = baseNuFee P M N m n :=
  liftEven_tmulEE _ _ _ _ _ _ _ _ m n

/-- The inner lift on odd-odd products. -/
@[simp] theorem baseNuInnerEven_tmulOO (m : M.odd) (n : N.odd) :
    baseNuInnerEven P M N (tmulOO M N m n) = baseNuFoo P M N m n :=
  liftEven_tmulOO _ _ _ _ _ _ _ _ m n

/-- The inner lift on even-odd products. -/
@[simp] theorem baseNuInnerOdd_tmulEO (m : M.even) (n : N.odd) :
    baseNuInnerOdd P M N (tmulEO M N m n) = baseNuFeo P M N m n :=
  liftOdd_tmulEO _ _ _ _ _ _ _ _ m n

/-- The inner lift on odd-even products. -/
@[simp] theorem baseNuInnerOdd_tmulOE (m : M.odd) (n : N.even) :
    baseNuInnerOdd P M N (tmulOE M N m n) = baseNuFoe P M N m n :=
  liftOdd_tmulOE _ _ _ _ _ _ _ _ m n

/-! ### The outer lift of the inverse comparison -/

/-- The even action of the residue module, on coordinates. -/
@[simp] theorem pointMod_actEE_down (b : S.even)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    ((pointMod P : S.Mod.{u, u, u, u}).actEE b a).down =
      P.chi b * a.down := rfl

/-- An even scalar crosses the inner lift in even degree. -/
theorem baseNuInnerEven_actEE (b : S.even)
    (t : (M.tensor N : S.Mod.{u, u, u, u}).even)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    baseNuInnerEven P M N ((M.tensor N).actEE b t) a =
      baseNuInnerEven P M N t ((pointMod P).actEE b a) := by
  refine LinearMap.congr_fun (liftEven_unique M N
    (((baseNuInnerEven P M N).flip a).comp
      ((M.tensor N : S.Mod.{u, u, u, u}).actEE b))
    ((baseNuInnerEven P M N).flip
      ((pointMod P : S.Mod.{u, u, u, u}).actEE b a))
    (fun m n => ?_) (fun m n => ?_)) t
  · simp only [LinearMap.comp_apply, LinearMap.flip_apply,
      actEE_tmulEE, baseNuInnerEven_tmulEE, baseNuFee_apply,
      tmulEE_actEE_pointOne, pointMod_actEE_down,
      TensorProduct.smul_tmul', Prod.smul_mk, smul_zero,
      smul_smul, mul_comm]
  · simp only [LinearMap.comp_apply, LinearMap.flip_apply,
      actEE_tmulOO, baseNuInnerEven_tmulOO, baseNuFoo_apply,
      tmulOE_actEO_pointOne, pointMod_actEE_down,
      TensorProduct.smul_tmul', Prod.smul_mk, smul_zero,
      smul_smul, mul_comm]

/-- An odd scalar kills the inner lift in even degree. -/
theorem baseNuInnerEven_actOO (c : S.odd)
    (t : (M.tensor N : S.Mod.{u, u, u, u}).odd)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    baseNuInnerEven P M N ((M.tensor N).actOO c t) a = 0 := by
  refine LinearMap.congr_fun (liftOdd_unique M N
    (((baseNuInnerEven P M N).flip a).comp
      ((M.tensor N : S.Mod.{u, u, u, u}).actOO c)) 0
    (fun m n => ?_) (fun m n => ?_)) t
  · simp only [LinearMap.comp_apply, LinearMap.flip_apply,
      actOO_tmulEO, baseNuInnerEven_tmulOO, baseNuFoo_apply,
      tmulOE_actOE_pointOne, TensorProduct.zero_tmul,
      smul_zero, LinearMap.zero_apply, Prod.mk_zero_zero]
  · simp only [LinearMap.comp_apply, LinearMap.flip_apply,
      actOO_tmulOE, baseNuInnerEven_tmulEE, baseNuFee_apply,
      tmulEE_actOO_pointOne, TensorProduct.zero_tmul,
      smul_zero, LinearMap.zero_apply, Prod.mk_zero_zero]

/-- An even scalar crosses the inner lift in odd degree. -/
theorem baseNuInnerOdd_actEO (b : S.even)
    (t : (M.tensor N : S.Mod.{u, u, u, u}).odd)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    baseNuInnerOdd P M N ((M.tensor N).actEO b t) a =
      baseNuInnerOdd P M N t ((pointMod P).actEE b a) := by
  refine LinearMap.congr_fun (liftOdd_unique M N
    (((baseNuInnerOdd P M N).flip a).comp
      ((M.tensor N : S.Mod.{u, u, u, u}).actEO b))
    ((baseNuInnerOdd P M N).flip
      ((pointMod P : S.Mod.{u, u, u, u}).actEE b a))
    (fun m n => ?_) (fun m n => ?_)) t
  · simp only [LinearMap.comp_apply, LinearMap.flip_apply,
      actEO_tmulEO, baseNuInnerOdd_tmulEO, baseNuFeo_apply,
      tmulEE_actEE_pointOne, pointMod_actEE_down,
      TensorProduct.smul_tmul', Prod.smul_mk, smul_zero,
      smul_smul, mul_comm]
  · simp only [LinearMap.comp_apply, LinearMap.flip_apply,
      actEO_tmulOE, baseNuInnerOdd_tmulOE, baseNuFoe_apply,
      tmulOE_actEO_pointOne, pointMod_actEE_down,
      TensorProduct.smul_tmul', Prod.smul_mk, smul_zero,
      smul_smul, mul_comm]

/-- An odd scalar kills the inner lift in odd degree. -/
theorem baseNuInnerOdd_actOE (c : S.odd)
    (t : (M.tensor N : S.Mod.{u, u, u, u}).even)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    baseNuInnerOdd P M N ((M.tensor N).actOE c t) a = 0 := by
  refine LinearMap.congr_fun (liftEven_unique M N
    (((baseNuInnerOdd P M N).flip a).comp
      ((M.tensor N : S.Mod.{u, u, u, u}).actOE c)) 0
    (fun m n => ?_) (fun m n => ?_)) t
  · simp only [LinearMap.comp_apply, LinearMap.flip_apply,
      actOE_tmulEE, baseNuInnerOdd_tmulOE, baseNuFoe_apply,
      tmulOE_actOE_pointOne, TensorProduct.zero_tmul,
      smul_zero, LinearMap.zero_apply, Prod.mk_zero_zero]
  · simp only [LinearMap.comp_apply, LinearMap.flip_apply,
      actOE_tmulOO, baseNuInnerOdd_tmulEO, baseNuFeo_apply,
      tmulEE_actOO_pointOne, TensorProduct.zero_tmul,
      smul_zero, LinearMap.zero_apply, Prod.mk_zero_zero]

variable (M N)

/-- **The inverse comparison in even degree.** -/
noncomputable def baseNuEven :
    ((M.tensor N).tensor (pointMod P) : S.Mod.{u, u, u, u}).even →ₗ[ℂ]
      basePairEven P M N :=
  liftEven (M.tensor N) (pointMod P) (baseNuInnerEven P M N) 0
    (fun b t a => baseNuInnerEven_actEE P b t a)
    (fun _ _ _ => rfl)
    (fun c t v => by
      show (0 : basePairEven P M N) = _
      rw [pointMod_actOO, map_zero])
    (fun c t a => by
      show baseNuInnerEven P M N ((M.tensor N).actOO c t) a = -0
      rw [baseNuInnerEven_actOO, neg_zero])

/-- **The inverse comparison in odd degree.** -/
noncomputable def baseNuOdd :
    ((M.tensor N).tensor (pointMod P) : S.Mod.{u, u, u, u}).odd →ₗ[ℂ]
      basePairOdd P M N :=
  liftOdd (M.tensor N) (pointMod P) 0 (baseNuInnerOdd P M N)
    (fun _ _ _ => rfl)
    (fun b t a => baseNuInnerOdd_actEO P b t a)
    (fun c t a => by
      show baseNuInnerOdd P M N ((M.tensor N).actOE c t) a = 0
      rw [baseNuInnerOdd_actOE])
    (fun c t v => by
      show (0 : basePairOdd P M N) = -_
      rw [pointMod_actOO, map_zero, neg_zero])

variable {M N}

/-- The inverse comparison in even degree, on generators. -/
@[simp] theorem baseNuEven_tmulEE
    (t : (M.tensor N : S.Mod.{u, u, u, u}).even)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    baseNuEven P M N (tmulEE (M.tensor N) (pointMod P) t a) =
      baseNuInnerEven P M N t a :=
  liftEven_tmulEE _ _ _ _ _ _ _ _ t a

/-- The inverse comparison in odd degree, on generators. -/
@[simp] theorem baseNuOdd_tmulOE
    (t : (M.tensor N : S.Mod.{u, u, u, u}).odd)
    (a : (pointMod P : S.Mod.{u, u, u, u}).even) :
    baseNuOdd P M N (tmulOE (M.tensor N) (pointMod P) t a) =
      baseNuInnerOdd P M N t a :=
  liftOdd_tmulOE _ _ _ _ _ _ _ _ t a

end InverseMap

/-! ## The comparison in super vector spaces -/

section SuperVectComparison

open scoped TensorProduct

variable {S : SuperCommAlgebra.{u, u}} (P : SuperPoint S)

variable (M N : S.Mod.{u, u, u, u})
  [FiniteDimensional ℂ (M.tensor (pointMod P)).even]
  [FiniteDimensional ℂ (M.tensor (pointMod P)).odd]
  [FiniteDimensional ℂ (N.tensor (pointMod P)).even]
  [FiniteDimensional ℂ (N.tensor (pointMod P)).odd]
  [FiniteDimensional ℂ ((M.tensor N).tensor (pointMod P)).even]
  [FiniteDimensional ℂ ((M.tensor N).tensor (pointMod P)).odd]

/-- **The comparison morphism in super vector spaces**, in even
degree, before the coordinates are installed. -/
noncomputable def superVectMuEvenRaw :
    ((M.tensor (pointMod P)).even ⊗[ℂ]
        (N.tensor (pointMod P)).even) ×
      ((M.tensor (pointMod P)).odd ⊗[ℂ]
        (N.tensor (pointMod P)).odd) →ₗ[ℂ]
      ((M.tensor N).tensor (pointMod P)).even :=
  (pointBaseMu P M N).evenMap ∘ₗ
    gradedTensorEven (M.tensor (pointMod P)) (N.tensor (pointMod P))

/-- **The comparison morphism in super vector spaces**, in odd
degree, before the coordinates are installed. -/
noncomputable def superVectMuOddRaw :
    ((M.tensor (pointMod P)).even ⊗[ℂ]
        (N.tensor (pointMod P)).odd) ×
      ((M.tensor (pointMod P)).odd ⊗[ℂ]
        (N.tensor (pointMod P)).even) →ₗ[ℂ]
      ((M.tensor N).tensor (pointMod P)).odd :=
  (pointBaseMu P M N).oddMap ∘ₗ
    gradedTensorOdd (M.tensor (pointMod P)) (N.tensor (pointMod P))

/-- The coordinates on the even part of the tensor product of the
two base changes. -/
noncomputable def superVectPairEvenEquiv :
    basePairEven P M N ≃ₗ[ℂ]
      (toSuperVect P M ⊗ toSuperVect P N).even :=
  LinearEquiv.prodCongr
    (TensorProduct.congr (toSuperVectEvenEquiv P M)
      (toSuperVectEvenEquiv P N))
    (TensorProduct.congr (toSuperVectOddEquiv P M)
      (toSuperVectOddEquiv P N))

/-- The coordinates on the odd part of the tensor product of the
two base changes. -/
noncomputable def superVectPairOddEquiv :
    basePairOdd P M N ≃ₗ[ℂ]
      (toSuperVect P M ⊗ toSuperVect P N).odd :=
  LinearEquiv.prodCongr
    (TensorProduct.congr (toSuperVectEvenEquiv P M)
      (toSuperVectOddEquiv P N))
    (TensorProduct.congr (toSuperVectOddEquiv P M)
      (toSuperVectEvenEquiv P N))

/-- **The monoidal comparison of the fibre functor**: the tensor
product of the base changes maps to the base change of the tensor
product.  It is the raw comparison, read in the coordinates that
`RS.toSuperVect` installs. -/
noncomputable def superVectMu :
    toSuperVect P M ⊗ toSuperVect P N ⟶ toSuperVect P (M.tensor N) where
  evenMap :=
    (toSuperVectEvenEquiv P (M.tensor N)).toLinearMap ∘ₗ
      superVectMuEvenRaw P M N ∘ₗ
      (superVectPairEvenEquiv P M N).symm.toLinearMap
  oddMap :=
    (toSuperVectOddEquiv P (M.tensor N)).toLinearMap ∘ₗ
      superVectMuOddRaw P M N ∘ₗ
      (superVectPairOddEquiv P M N).symm.toLinearMap

end SuperVectComparison

/-! ## The four summands of a tensor product of super vector spaces

The even part of `V ⊗ W` is a sum of two blocks and so is the odd
part.  Naming the four inclusions keeps every generator below at
its structural type, which is what lets the rewriting see through
the tensor product of super vector spaces. -/

section Summands

open scoped TensorProduct

/-- The even-even block of the even part. -/
def svEvenInl {V W : SuperVect} (t : V.even ⊗[ℂ] W.even) :
    (V ⊗ W).even := (t, 0)

/-- The odd-odd block of the even part. -/
def svEvenInr {V W : SuperVect} (t : V.odd ⊗[ℂ] W.odd) :
    (V ⊗ W).even := (0, t)

/-- The even-odd block of the odd part. -/
def svOddInl {V W : SuperVect} (t : V.even ⊗[ℂ] W.odd) :
    (V ⊗ W).odd := (t, 0)

/-- The odd-even block of the odd part. -/
def svOddInr {V W : SuperVect} (t : V.odd ⊗[ℂ] W.even) :
    (V ⊗ W).odd := (0, t)

/-- The odd-odd block of zero vanishes. -/
theorem svEvenInr_zero {V W : SuperVect} :
    svEvenInr (0 : V.odd ⊗[ℂ] W.odd) = 0 := rfl

/-- The even-odd block of zero vanishes. -/
theorem svOddInl_zero {V W : SuperVect} :
    svOddInl (0 : V.even ⊗[ℂ] W.odd) = 0 := rfl

/-- The odd-even block of zero vanishes. -/
theorem svOddInr_zero {V W : SuperVect} :
    svOddInr (0 : V.odd ⊗[ℂ] W.even) = 0 := rfl

end Summands

/-! ## The comparison on generators of the tensor product -/

section MuBlocks

open scoped TensorProduct

variable {S : SuperCommAlgebra.{u, u}} (P : SuperPoint S)
  (M N : S.Mod.{u, u, u, u})
  [FiniteDimensional ℂ (M.tensor (pointMod P)).even]
  [FiniteDimensional ℂ (M.tensor (pointMod P)).odd]
  [FiniteDimensional ℂ (N.tensor (pointMod P)).even]
  [FiniteDimensional ℂ (N.tensor (pointMod P)).odd]
  [FiniteDimensional ℂ ((M.tensor N).tensor (pointMod P)).even]
  [FiniteDimensional ℂ ((M.tensor N).tensor (pointMod P)).odd]

variable {M N}

/-- The comparison on an even-even generator. -/
theorem superVectMu_evenMap_ee (x : (toSuperVect P M).even)
    (y : (toSuperVect P N).even) :
    (superVectMu P M N).evenMap (svEvenInl (x ⊗ₜ[ℂ] y)) =
      toSuperVectEvenEquiv P (M.tensor N)
        ((pointBaseMu P M N).evenMap
          (tmulEE (M.tensor (pointMod P)) (N.tensor (pointMod P))
            ((toSuperVectEvenEquiv P M).symm x)
            ((toSuperVectEvenEquiv P N).symm y))) := rfl

/-- The comparison on an odd-odd generator. -/
theorem superVectMu_evenMap_oo (x : (toSuperVect P M).odd)
    (y : (toSuperVect P N).odd) :
    (superVectMu P M N).evenMap (svEvenInr (x ⊗ₜ[ℂ] y)) =
      toSuperVectEvenEquiv P (M.tensor N)
        ((pointBaseMu P M N).evenMap
          (tmulOO (M.tensor (pointMod P)) (N.tensor (pointMod P))
            ((toSuperVectOddEquiv P M).symm x)
            ((toSuperVectOddEquiv P N).symm y))) := rfl

/-- The comparison on an even-odd generator. -/
theorem superVectMu_oddMap_eo (x : (toSuperVect P M).even)
    (y : (toSuperVect P N).odd) :
    (superVectMu P M N).oddMap (svOddInl (x ⊗ₜ[ℂ] y)) =
      toSuperVectOddEquiv P (M.tensor N)
        ((pointBaseMu P M N).oddMap
          (tmulEO (M.tensor (pointMod P)) (N.tensor (pointMod P))
            ((toSuperVectEvenEquiv P M).symm x)
            ((toSuperVectOddEquiv P N).symm y))) := rfl

/-- The comparison on an odd-even generator. -/
theorem superVectMu_oddMap_oe (x : (toSuperVect P M).odd)
    (y : (toSuperVect P N).even) :
    (superVectMu P M N).oddMap (svOddInr (x ⊗ₜ[ℂ] y)) =
      toSuperVectOddEquiv P (M.tensor N)
        ((pointBaseMu P M N).oddMap
          (tmulOE (M.tensor (pointMod P)) (N.tensor (pointMod P))
            ((toSuperVectOddEquiv P M).symm x)
            ((toSuperVectEvenEquiv P N).symm y))) := rfl

end MuBlocks

end RS
